### ISSUE TITLE
QUERY: how to convert signature from webcrypto into form suitable for ecdsa.verify?

### ISSUE THREAD

**Issue by brave-dev** [bitchan/eccrypto#11]
let's say i'm using webcryptography in the browser and have some code like this:

    var payload = {}
    var combo = JSON.stringify({ ... })

    var ab2b = function (ab) {
        var buffer = []
        var view = new Uint8Array(ab)

        for (var i = 0; i < ab.byteLength; i++) buffer[i] = view[i]
        return buffer
    }

    var s2ab = function (s) {
        var buffer = new Uint8Array(s.length)

        for (var i = 0; i < s.length; i++) buffer[i] = s.charCodeAt(i)
        return buffer
    }

    var to_hex = function (bs) {
        var encoded = []

        for (var i = 0; i < bs.length; i++) {
            encoded.push('0123456789abcdef'[(bs[i] >> 4) & 15])
            encoded.push('0123456789abcdef'[bs[i] & 15])
        }
        return encoded.join('')
    }

    window.crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' },
                                     true, [ 'sign', 'verify' ]).then(function (pair) {
        window.crypto.subtle.exportKey('raw', pair.publicKey).then(function (publicKey) {
            window.crypto.subtle.sign({ name: 'ECDSA', hash: { name: 'SHA-256' } },
                                      pair.privateKey, s2ab(combo)).then(function(signature) {
                payload.publicKey = to_hex(ab2b(publickKey)
                payload.signature = to_hex(ab2b(signature)
            })
        })
    })

what i am trying to figure out is how to take the two values in payload that contain hex-encoded strings and invoke ecdsa.verify() appropriately:

    var crypto = require('crypto')
    var ecdsa = require('eccrypto')
    
    var reverse = function(s) {
      var array = []
    
      for (var i = s.length - 2; i >= 0; i -= 2) array.push(s.substr(i, 2))
    
      return array.join('')
    }
    
    var from_hex = function (s) {
      var i, result
    
      if (!s) s = ''
      result = new Uint8Array(s.length / 2)
      for (i = 0; i < s.length / 2; i++) result[i] = parseInt(s.substr(i * 2, 2), 16)
    
      return result
    }
    
    var userId     = '213B6A73-4A53-4E63-BEDB-26AB2C8AA227'
     , message     =
    {
      "header": {
        "signature": "11e05bb6c5cc0980d8611a1e7921423b0aa6a3440257a7ed984aab4ffc5034fe0abce2e9e03b41f7544deecb3eac2315f6027a6676ef706dcb8737913355af34",
        "nonce": "1449333073.463"
      },
      "payload": {
        "version": 1,
        "publicKey": "04cb67681175709c99baba9514094078028857ec8633d6273886222bee7a604a4c721743c7344498792c5f1f78aabfa03805d28c4544cfe3ed63dabde10bc529d9"
      }
    }
      , combo      = JSON.stringify({ userId: userId, nonce: message.header.nonce, payload: message.payload })
      , r          = message.header.signature.substr(0, 64)
      , s          = message.header.signature.substr(64, 64)
      , options    =
      { r: reverse(r)
      , s: reverse(s)
      }
    
    console.log(options)
    
    ecdsa.verify(from_hex(message.payload.publicKey), crypto.createHash('sha256').update(combo).digest(),
                 options).then(function () {
      console.log('winner')
    }).catch(function (ex) {
      console.log('loser')
      console.log(ex)
    })

thanks!

/mtr

**Comment by Kagami** [comment]
I see 2 possible errors:
* You need to use `K-256` curve with WebCryptoAPI (wasn't available in major browsers last time I checked)
* Third argument of `eccrypto.verify` should be signature in DER format, now you're passing object

And I'm not sure you can hash passed message with `subtle.sign`, you might need to do it separately. Also, just a hint: try to simplify your example, hardcode 65-byte public key & 32-byte message in both implementations and make sure it works for a simplest case.

**Comment by Kagami** [comment]
Regarding `subtle.sign` result to `DER`: according to [docs](http://www.w3.org/TR/WebCryptoAPI/#ecdsa-operations) they're laying sequantially in the buffer (you're already picking them up), so all you need is to convert `R` & `S` to `DER`. You can use e.g. `elliptic` library for that, see [here](https://github.com/indutny/elliptic/blob/v6.0.2/lib/elliptic/ec/signature.js#L108).

Though I'm not sure whether its format is compatible with `elliptic` like you already asked [here](https://github.com/indutny/elliptic/issues/61). But as long as you can verify `R` & `S` from `WebCryptoAPI` with `elliptic`, it should work in this library too (for the K-256 curve).

**Comment by brave-dev** [comment]
many thanks! i'll be AFK for a few hours, but plan to get back on this then.

**Comment by Kagami** [comment]
Posted example in abovementioned issue. As soon as you get proper `R` and `S`, just use `Signature` class from `elliptic` in oder to export them to `DER`. You probably won't be able to use `WebCryptoAPI` with `eccrypto` though because browsers don't support `K-256` curve.
