### ISSUE TITLE
Improve unittesting by means of Saucelabs and Codeclimate

### ISSUE THREAD

**Issue by evilaliv3** [bitchan/eccrypto#13]
I would suggest that in order to verify the compatibility of the library with the various trargetted browsers and in order to keep track of various code quality indicator you could implement integration with [Saucelabs](saucelabs.com) and [Codeclimate](https://codeclimate.com)

i'm thinking this while evaluating the validity of the eccrypto for the integration in openpgp.js (https://github.com/openpgpjs/openpgpjs/issues/428), and i've right know implemented what i'm suggesting to you for the https://github.com/indutny/elliptic project: https://github.com/indutny/elliptic/pull/80

It would be great if you could do the same!

![screenshot from 2016-03-22 18 18 31](https://cloud.githubusercontent.com/assets/217034/13961139/93c4c6bc-f05b-11e5-8a68-6f02493a21f8.png)

**Comment by Kagami** [comment]
Sounds good. PRs are welcome.
(Btw eccrypto is currently tested against Firefox 34 and Ubuntu's Chromium with Karma.)

**Comment by JBaczuk** [comment]
Closing this because it looks like saucelabs and codeclimate are only paid software, and the openpgjs already implemented ecc https://github.com/openpgpjs/openpgpjs/pull/618
