### ISSUE TITLE
secp256k1?

### ISSUE THREAD

**Issue by pupeno** [bitchan/eccrypto#14]
In the README, it says:

> **Only secp256k1 curve**, only SHA-512 (KDF), HMAC-SHA-256 (HMAC) and AES-256-CBC for ECIES

and then it says:

> Also WebCryptoAPI currently defines only curves recommended by NIST meaning that **secp256k1 (K-256) curve is not supported** (see also: [1], [2]).

Is this library using secp256k1 or not?

There's a link after that with text "seck256k1" that actually points to https://www.npmjs.com/package/secp256k1

So, which curve does this library use?

**Comment by Kagami** [comment]
WebCryptoAPI doesn't support K-256 (i.e. browsers don't support K-256 natively), so this library uses standalone implementation of that curve.
