### ISSUE TITLE
Why is the path to the openssl lib static ?

### ISSUE THREAD

**Issue by Mayhem93** [bitchan/eccrypto#17]
I'm trying to install gencryption npm package which relies on this one and I can't make it to install under windows.

I got **vcpkg** installed and ran the command to integrate the packages in a user-wide manner.

```
PS [12:17:16PM] C:\Users\uther\workspace# vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use -DCMAKE_TOOLCHAIN_FILE=C:/Users/uther/workspace/vcpkg/scripts/buildsystems/vcpkg.cmake
```

I can't install this package because of the linker error: `LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\uther\workspace\people-ai-worker\node_modules\eccrypto\build\ecdh.vcxproj]` (because **obviously** there's nothing there)

PS: I don't know what's the best practice when using external libs and windows

**Comment by Mayhem93** [comment]
Here, have a read on this https://github.com/justmoon/node-bignum/issues/101 about my potential solution to this issue

**Comment by JBaczuk** [comment]
Closing this as over a year old, it's unclear if its an eccrypto issue or just Windows.  Also, I don't have Windows to debug this. If you'd like to reopen let me know.
