### ISSUE TITLE
Validate keys and input

### ISSUE THREAD

**Issue by Kagami** [bitchan/eccrypto#2]
All keys and input must be validated before any processing in order to avoid implementation specific vulnerabilities against corrupted input parameters.

**Comment by Kagami** [comment]
See also: https://github.com/bitcoin/secp256k1/issues/43#issuecomment-47997596
There are should be checks for bad key when signing, when deriving, when encrypting.

**Comment by Kagami** [comment]
Probably most of this already done, maybe still needed some additional checkings for keys and signature.

**Comment by englercj** [comment]
Why is the private key limited to 32 bytes? I notice in that thread they say the *message* must be limited to 32-bytes, but can't find anything about ecdsa private keys having to be exactly 32-bytes?

In fact, openssl generates keys larger than 32-bytes for ecdsa:

```
openssl ecparam -name secp256k1 -genkey -noout -out secp256k1-key.pem // output larger than 32-bytes
ssh-keygen -t ecdsa // larger than 32-bytes
```

**Comment by Kagami** [comment]
>Why is the private key limited to 32 bytes?

See e.g. [here](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm#Signature_generation_algorithm).
`dA` must be in range `[1, n - 1]`, `n` is [`FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE BAAEDCE6 AF48A03B BFD25E8C D0364141`](https://en.bitcoin.it/wiki/Secp256k1) for K-256 curve (almost 32 bytes).

>In fact, openssl generates keys larger than 32-bytes for ecdsa

Because its output is in [DER format](https://en.wikipedia.org/wiki/X.690#DER_encoding). You can check the key details with e.g. `openssl ec -text -noout < id_ecdsa`. `priv` part for K-256 curve is 256 bit.

**Comment by englercj** [comment]
@Kagami Ahh! Good call, didn't realize it was in DER format. Thanks for the knowledge!
