### ISSUE TITLE
generating bitcoin private key from 512 bit seed

### ISSUE THREAD

**Issue by se8820726** [bitchan/eccrypto#27]
Hi 
I want to generate bitcoin private key from a 512 bit seed.
can I do this with your library and how ?
please give me example

**Comment by JBaczuk** [comment]
Sorry, this library currently doesn't have that kind of wallet-specific functionality, it is focused only on cryptography using the `secp256k1` elliptic curve (ECDSA, ECDH and ECIES). I would recommend looking into something like [bitcoinjs-lib](https://github.com/bitcoinjs/bitcoinjs-lib), which has more wallet functionality.
