### ISSUE TITLE
browser.js randomBytes on IE11

### ISSUE THREAD

**Issue by letspkt** [bitchan/eccrypto#28]
`getRandomValues` of undefined error is raised on IE11 browser.
```
function randomBytes(size) {
  var arr = new Uint8Array(size);
  global.crypto.getRandomValues(arr);
  return new Buffer(arr);
}
```
I think global.crypto needs to be replaced with cryptoObj in the randomBytes function. Any suggestions?

**Comment by JBaczuk** [comment]
Are you using browserify?

**Comment by JBaczuk** [comment]
Thanks for the tip, it looks like it needs to use `window.msCrypto.getRandomValues()`, which using `cryptoObj` would fix. Just need to test it.
