### ISSUE TITLE
Bad public key Exception

### ISSUE THREAD

**Issue by leduyhung** [bitchan/eccrypto#36]
Hi !

First thing i want to say thank you for your amazing library.

Currently i have trouble. I use this library to generate public and private key on node server, then return to android client public key. I import success public key and verify complete in android client, but when i use public key for encrypt (ECIES) and post to node server to decrypt it, node server throw bad public key exception.

I hope will receive your reply soon !

Thanks !

**Comment by JBaczuk** [comment]
Can you show code to reproduce this, please?

**Comment by leduyhung** [comment]
Actually i found solution. My mistake is send only text cipher to server and used your lib to decrypt it, so your library not found client ephemPublicKey, IV and MAC. 

Btw, thank you for your response. you can close this issue !
