### ISSUE TITLE
Provide a way to create a valid private key

### ISSUE THREAD

**Issue by ea2973929** [bitchan/eccrypto#37]
In examples on how to use eccrypto, private keys are often generated using

`crypto.randomBytes(32)`

Within the source code of eccrypto it's noted though that this might not be a valid keys and internally the following code is used for ephemPrivateKey: 

```
while(!isValidPrivateKey(ephemPrivateKey))
{
      ephemPrivateKey = opts.ephemPrivateKey || crypto.randomBytes(32);
}

function isValidPrivateKey(privateKey) {
  if (!isScalar(privateKey))
  {
    return false;
  }
  return privateKey.compare(ZERO32) > 0 && // > 0
  privateKey.compare(EC_GROUP_ORDER) < 0; // < G
}
```
As a user I would first of all need to know this, and secondly create my own function to do the same thing. `isValidPrivateKey` is not exported. 

It would be greatly appreciated if this could be abstracted away and provided in a function: `eccrypto.generatePrivateKey()`. Alternatively at least `isValidPrivateKey` could be exported.

**Comment by JBaczuk** [comment]
I like this idea.
