### ISSUE TITLE
[Question] How can I load a preexisting key for user in this lib

### ISSUE THREAD

**Issue by englercj** [bitchan/eccrypto#5]
How can I load an existing openssl generated, `.pem` encoded, private key to use with this lib?

Sorry if this is a stupid question...

What I tried was loading the base64 data and just loading it into a buffer, but as you mentioned that is just the DER encoded key. How can I decode that for use here?

Thanks!

To generate the private key I am using:

```
openssl ecparam -name secp256k1 -genkey -noout -out secp256k1-key.pem
```

I will also likely be generating the public key outside of this module, so I would like to load them not create them in code.

**Comment by Kagami** [comment]
Hi. Here is example code which decodes pem key using the [asn1.js](https://github.com/indutny/asn1.js) library:

```js
var fs = require("fs");
var asn = require("asn1.js");

var pem = fs.readFileSync("secp256k1-key.pem", "utf8");
var der_b64 = pem.match(/-----$([^]+)^-----/m)[1];
var der = Buffer(der_b64, "base64");
var Key = asn.define("Key", function() {
  this.seq().obj(
    this.key("_n").int(),
    this.key("priv").octstr()
  );
});
var key = Key.decode(der, "der");
console.log(key.priv);
console.log(key.priv.length);
```

probably you can make it better (e.g. by reading at specific offset and decoding the ASN.1 by yourself), this is just an example.

**Comment by Kagami** [comment]
Hope you made it work. Closing. Feel free to ask additional questions if somethings is still not clear.
