### ISSUE TITLE
Intermittent Decryption Failure (1/1000+ so far), reproduced once

### ISSUE THREAD

**Issue by AC-FTW** [bitchan/eccrypto#52]
### Problem:
I'm using eccrypto in both browser & node in a system and am observing a decryption failure.  In the browser I'm encountering this error with specific data (so far this has been replicated once in about 1000+ uses
[decryption-problem.zip](https://github.com/bitchan/eccrypto/files/4242205/decryption-problem.zip)
):
`"Uncaught Error: The error you provided does not contain a stack trace."`

When I move the same data and use case to node, I get the following error:
```
Failed with error: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (internal/crypto/cipher.js:183:29)
    at aes256CbcDecrypt (/Users/.../node_modules/eccrypto/index.js:61:28)
    at /Users/.../node_modules/eccrypto/index.js:256:66
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async tryDecrypting (/Users/.../index.js:44:18) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}

```
The associated private key was created using the eccrypto library on a browser, here is what that code looks like:
```
    const priKey = eccrypto.generatePrivate()
    const pubKey = eccrypto.getPublic(priKey)

```
This works most of the time (i.e. upwards of 1/1000), however I'd like to understand this particular failure as this rate of failure is still too high.

One important note is that private keys are being encrypted/decrypted on an HSM and stored in binary on a DB. Also the cipher text object is being stored in binary on a DB.  We could change that to base 64 and possibly look at applying ECC or other techniques to ensure data integrity, but it's not clear to me that is the issue.

I've attached an example node project with the failing data (key and ciphertext).  To run it:

1. unzip
2. npm install
3. node index.js

[decryption-problem.zip](https://github.com/bitchan/eccrypto/files/4242218/decryption-problem.zip)

**Comment by AC-FTW** [comment]
Note:  the 1000+ figure is when encryption/decryption cycles were both browser based.  The figure is lower (~100) now that encryption is server side and decryption remains on a browser.

**Comment by AC-FTW** [comment]
After trying to decrypt with a different library based  loosely on this one (https://github.com/tibetty/ecies-lite#readme), I get the following error which I believe is telling me the mac is incorrect:

Failed with error: Error: Corrupted Ecies-lite body: unmatched authentication code
    at Object.exports.decrypt (/Users/.../node_modules/ecies-lite/index.js:78:19)
    at tryEciesLite (/Users/.../index.js:60:34)
    at main (/Users/.../index.js:70:9)
    at Object.<anonymous> (/Users/.../index.js:74:1)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11

**Comment by AC-FTW** [comment]
So far, I've managed to trace this to an environment problem between two machines--on one machine the encrypt function creates something that can be decrypted. On the other machine, the cipher text cannot be decrypted.  Comparing package-lock.json and the captured output of npm install is fruitless unfortunately.

If anyone has any suggestions on a way to meaningfully compare the the library in the two environments, please do let me know.

**Comment by JBaczuk** [comment]
Sorry for the late reply, I'm not sure the difference between the machines, if you can provide more info it would be helpful. Closing for now, please re-open if you still need help.
