### ISSUE TITLE
there is a prefix '04' in every public key generated

### ISSUE THREAD

**Issue by maroodb** [bitchan/eccrypto#58]
Hello World
I am using eccrypto to generate key pair at the clien side (javascript)
and verify signature at the server side (java). 

I noticed that there is always a prefix "04" added to public key using eccrypto. 

example: 

```
const privateKey = Buffer.from('e12c017eaada16e2355e85d52e366a99b6ef5b871e2a4ef15a33861cdfbc276e, 'hex')

const  publicKey = eccrypto.getPublic(privateKey); 
const publicKeyHex = publicKey.toString('hex')
 /* returns  040497cee5d2317fed4a79aeb13a6e50958ba3b928319d185c3faf05a7e0e859c0e45bfe5cec402529b92f07cf2341c44f3ca954ad727f58dfe096e9c5cafda51e7d*/
```

Using java security from the same privateKey I got :

`97cee5d2317fed4a79aeb13a6e50958ba3b928319d185c3faf05a7e0e859c0e45bfe5cec402529b92f07cf2341c44f3ca954ad727f58dfe096e9c5cafda51e7d`
without leading "04"

**I tried many examples and always there is a leading "04"**

any explantation please ?

**Comment by tetratorus** [comment]
04 is the prefix for showing that the public key is in the full uncompressed format

**Comment by JBaczuk** [comment]
Closing as answered
