### ISSUE TITLE
Private key range

### ISSUE THREAD

**Issue by Kagami** [bitchan/eccrypto#6]
See http://procbits.com/2013/08/27/generating-a-bitcoin-address-with-javascript, https://github.com/cryptocoinjs/eckey/issues/13.
We should **exactly** understand what's going on if secret key is >= `n`.

**Comment by JBaczuk** [comment]
This is governed by the ECDSA specification, and signature may fail.  Most implementations of ECDSA for secp256k1 don't allow keys beyond `0xFFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFE BAAE DCE6 AF48 A03B BFD2 5E8C D036 4140` so we might as well not allow it either.
