### ISSUE TITLE
Writing public key to file

### ISSUE THREAD

**Issue by matthewh** [bitchan/eccrypto#7]
Do you have an example of writing the public key to disk in DER or ascii armored format? I have been unsuccessful inspecting keys generated with eccrypto. I'm using nodejs.

```
  	var crypto = require("crypto");
  	var eccrypto = require("eccrypto");
        var fs = require('fs');
  	// A new random 32-byte private key.
  	var privateKey = crypto.randomBytes(32);
  	// Corresponding uncompressed (65-byte) public key.
  	var publicKey = eccrypto.getPublic(privateKey);

	fs.writeFile("public_key", publicKey, function(err) {
		if (err) {
			return console.log(err);
		}
		console.log("The file was saved!");
	});

```

```
openssl ec -inform DER -in public_key -pubin
read EC key
unable to load Key
14938:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:/SourceCache/OpenSSL098/OpenSSL098-52.10.1/src/crypto/asn1/asn1_lib.c:153:
```

**Comment by Kagami** [comment]
Similar to #5 you need to encode ASN.1 data by yourself using some library because `eccrypto` gives you just bare public key. Here is example:

```js
var fs = require("fs");
var crypto = require("crypto");
var eccrypto = require("eccrypto");
var asn = require("asn1.js");

var Key = asn.define("Key", function() {
  this.seq().obj(
    this.key("algorithm").seq().obj(
      this.key("id").objid(),
      this.key("curve").objid()
    ),
    this.key("pub").bitstr()
  );
});

var privateKey = crypto.randomBytes(32);
var publicKey = eccrypto.getPublic(privateKey);
var pem = Key.encode({
  algorithm: {
    // :id-ecPublicKey
    id: [1, 2, 840, 10045, 2, 1],
    // :secp256k1
    curve: [1, 3, 132, 0, 10],
  },
  pub: {
    unused: 0,
    data: publicKey,
  },
}, "pem", {label: "PUBLIC KEY"});
fs.writeFileSync("pub.pem", pem + "\n");
```

```bash
$ openssl ec -pubin -text -noout < pub.pem
read EC key
Private-Key: (256 bit)
pub: 
    04:bd:72:f1:33:8c:db:f1:6a:94:3a:c1:98:6c:e4:
    91:78:81:bc:86:ff:e4:a7:1d:92:83:e7:32:1d:79:
    fb:1a:4f:6a:4e:a3:8e:f7:04:13:3c:e7:dc:ec:8f:
    5d:c9:ee:54:24:3b:3e:31:c4:e9:ad:57:df:d8:2d:
    00:b6:79:0e:20
ASN1 OID: secp256k1
```

Does this solve your problem?

**Comment by matthewh** [comment]
This looks promising. Thank you! I was using [elliptic](https://github.com/indutny/elliptic) because I eventually need to support secp384r1 but when I ran into problems exporting the key I was unable to discern if my curve configuration was wrong or I wasn't exporting the data correctly.

**Comment by matthewh** [comment]
I also need to export the private key in PKCS8 but I don't know where to begin. I can see that I need to define a different Key but I don't know what values to use. Can you point me to any documentation that describes the id and curve values used for algorithm? Any information would be greatly appreciated.

**Comment by Kagami** [comment]
Sure. Simplest way is to pick some already encoded openssl PEM key and run `openssl asn1parse < key.pem`. You will get the details about ASN internals. Then, if you're not sure about some params/OIDs you may either decode the key (see example in #5) and check the values, or find them in corresponding RFCs:
https://tools.ietf.org/html/rfc5915
https://tools.ietf.org/html/rfc5480
