### ISSUE TITLE
Release binary

### ISSUE THREAD

**Issue by dcharbonnier** [bitchan/eccrypto#73]
Providing the binary for this module would save a lot of time when installing it (time to install the build dependencies, time to build the code, time to clean the build dependencies) and some space in the docker layers (an extra layer with build dependencies).
90% of my `npm -ci` is dedicated to this module on many projects.
Would you be open to considering something like https://github.com/mapbox/node-pre-gyp ?

**Comment by itinance** [comment]
Do you really like to trust a pre-compiled binary? I would not do that, and I would recommend the same to you.

**Comment by dcharbonnier** [comment]
Yes, I would love it, especially coming from an automatic build.
I think if we have to read all the code every-time we build something it's gonna be very time consuming. I would recommend you to not do that when you upgrade your linux kernel for example.
